# -*- coding: utf-8 -*-
"""En_to_Egy_Spider_Data_NAMAA_Space.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MB7mmlaUU-4Aga3SVF7DM5PJJWC5Vjjp

# masrawy-english-to-egyptian-arabic-translator-v2.9 Inference
"""

from transformers import pipeline
def translateENtoEGY(question):
  modelName = "NAMAA-Space/masrawy-english-to-egyptian-arabic-translator-v2.9"
  translator = pipeline("translation", model=modelName)
  output = translator(question)
  print(output[0]['translation_text'])
  return output[0]['translation_text']

import json


# Paths
input_file = "test.json"
output_file = "test_translated.json"

# Load the JSON data
with open(input_file, "r", encoding="utf-8") as f:
    data = json.load(f)

# Iterate over each entry and add question_egy
for entry in data:
    if "question" in entry:
        entry["question_egy"] = translateENtoEGY(entry["question"])

# Save the modified JSON
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=4)

print(f"Saved translated file to {output_file}")


